# Bot情報
[botInfo]
bot_name = "tanenobot" # Botのusername
channel = "tanenob" # Botを送り込むTwitchチャンネル
TWITCH_TOKEN = "oauth:xxxxxxxx" # oauth: から始まるトークン
CLIENT_ID = "xxxxxxxx"

[shoutout]
enable_shoutout = true # shoutoutコマンド時にメッセージを出すか
shoutout_commands = [
    '!so',
    '!shoutout'
]
shoutout_message = """
§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§
- - - - - Please check this awesome streamer!! - - - - - -
この素晴らしい配信者もチェックしてください！ - - 
{displayName} : https://twitch.tv/{username}
最近の配信 Recent stream : {game} - {title}
§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§
"""
enable_raid_shoutout = true # レイド時にメッセージを出すか
raid_message = """
§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§
- - - - - We got raid by {username} with {viewers} viewers!  - - - - - -
襲撃だ！！ - - 
{displayName} : https://twitch.tv/{username}
最近の配信 Recent stream : {game} - {title}
§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§
"""
# メッセージの変数
# username: Twitchのアルファベットのユーザーネーム(例. 「tanenob」)
# displayName: Twitchの表示名(例. 「たねのぶ」)
# game: Raiderのゲームカテゴリ (例. 「Pogostuck: Rage With Your Friends」)
# title: Riaderの配信タイトル (例. 「ポゴ楽しい」)
# viewers: レイド時の人数

# 無視するusernameを入れる
ignore_users= [
    'Nightbot',
    'StreamElements',
    'Streamlabs',
    'tanenobot'
]