# Bot情報
[botInfo]
bot_name = "tanenobot" # Botのusername
channel = "tanenob" # Botを送り込むTwitchチャンネル
TWITCH_TOKEN = "oauth:xxxxxx" # oauth: から始まるトークン
CLIENT_ID = "xxxxxx" # Twitch Developersで取得したclient_id

# 無視するusernameを入れる
ignore_users = [
    'Nightbot',
    'StreamElements',
    'Streamlabs',
    'tanenobot'
]

[shoutout]
enable_shoutout = true # shoutoutコマンド時にメッセージを出すか (true / false)

# shoutoutコマンドが可能なユーザー broadcaster, moderator, subscriber, vip, everyone
user_levels = [
    'broadcaster',
    'moderator',
    # 'subscriber',
    # 'vip',
    # 'everyone'
]

# shoutoutコマンド(!から始めてください)
shoutout_commands = [
    '!so',
    '!shoutout'
]

# shoutoutメッセージ
shoutout_message = """
§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§
- - - - - Please check this awesome streamer!! - - - - - -
この素晴らしい配信者もチェックしてください！ - - 
{displayName} : https://twitch.tv/{username}
最近の配信 Recent stream : {game} - {title}
§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§
"""

 # レイド時にメッセージを出すか  (true / false)
enable_raid_shoutout = true

 # レイド時に音声(sounds/raid.wav)を出すか  (true / false)
enable_raid_sound = false

# レイド時のメッセージ
raid_message = """
§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§
- - - - - We got raid by {username} with {viewers} viewers!  - - - - - -
襲撃だ！！ - - 
{displayName} : https://twitch.tv/{username}
最近の配信 Recent stream : {game} - {title}
§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§=§
"""


# メッセージの変数
# username: Twitchのアルファベットのユーザーネーム(例. 「tanenob」)
# displayName: Twitchの表示名(例. 「たねのぶ」)
# game: 【レイド限定】Raiderのゲームカテゴリ (例. 「Pogostuck: Rage With Your Friends」)
# title: 【レイド限定】Riaderの配信タイトル (例. 「ポゴ楽しい」)
# viewers: 【レイド限定】レイド時の人数